### ISSUE TITLE
Terraform support

### ISSUE THREAD

**Issue by riaan53** [UpCloudLtd/upcloud-go-api#35]
Hi,

Any plans to provide a https://www.terraform.io/ golang plugin?

Thanks

**Comment by jgabor** [comment]
Thanks for the great suggestion! It's definitely in our plans and should not be too far into the future, but we got nothing concrete as of right now. We will update this issue when we have a better idea of the timeline.

**Comment by riaan53** [comment]
Thanks! This will be fantastic :)

**Comment by vtorhonen** [comment]
@jgabor Any updates? Are you already implementing this? Just asking to make sure people won't reinvent the wheel. I can help or start working from scratch if there's no progress yet.

**Comment by iler** [comment]
Hi @vtorhonen! We have not yet started implementing this as we've had other things with higher priority in our development queue. So if you could help us by starting the development efforts for the Terraform provider that would be super! Could you drop me a line via email so that we could work this out together?

**Comment by iler** [comment]
For all the interested the Terraform module development has been started at https://github.com/vtorhonen/terraform-provider-upcloud. All contributions should be done there.
